spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service
    username : postgres
    password : admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 25